# Generated by Django 3.1.6 on 2021-03-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
                ('body', models.CharField(max_length=2000)),
                ('category', models.CharField(max_length=100)),
                ('content_type', models.CharField(max_length=100)),
                ('source_link', models.CharField(max_length=1000)),
                ('image_link', models.CharField(max_length=1000)),
                ('tags', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('published_time', models.TimeField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
